### ISSUE TITLE
Doesn't Ask For Proper Permissions

### ISSUE THREAD

**Issue by janagyjr** [GlobalGamer2015/Odysee-Chatter-Bot#18]
I was going to install the bot just for my user (Windows 10 Pro) and instead of dropping it in AppData, it still tried to install into C:\Program Files\ w/o asking for proper admin permissions.

**Comment by GlobalGamer2015** [comment]
The admin permissions is a issue that I've been trying to fix.

**Comment by janagyjr** [comment]
If I might suggest, if the user chooses to only allow the bot for themselves on the system, install into `C:\Users\<name>\.Appdata\` instead, shouldn't need permissions then and the bot is only for that particular user. Just a thought.

**Comment by GlobalGamer2015** [comment]
Great idea, moving this to [suggestions](https://github.com/GlobalGamer2015/Odysee-Chatter-Bot/projects/1) tab.
